#!/usr/bin/env python
import sys

from TetrisGame import Board

board = Board(height=10)
for row in sys.stdin:
    commands = row.strip().split(",")
    for command in commands:
        command = command.strip()
        board.put_piece(command[0], command[1])
    print(board.max_height)
    board.clear()
